# Generated by Django 4.2.24 on 2026-02-09 10:44

import core.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to=core.models.user_image_upload_path)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('parent', 'Parent/Carer'), ('moe_admin', 'MoE Admin'), ('municipality_analyst', 'Municipality Analyst'), ('teacher', 'Teacher')], max_length=30)),
                ('whatsapp_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('temp_password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administrative_posts',
                'ordering': ['municipality__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_number', models.CharField(max_length=15)),
                ('template_type', models.CharField(choices=[('verification', 'Account Verification'), ('monthly_report', 'Monthly Progress Report'), ('enrollment_info', 'Preschool Enrollment Info')], max_length=30)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], max_length=20)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'indexes': [models.Index(fields=['to_number'], name='whatsapp_me_to_numb_2c6a97_idx'), models.Index(fields=['template_type', 'sent_at'], name='whatsapp_me_templat_56ebbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('administrative_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucos', to='core.administrativepost')),
            ],
            options={
                'db_table': 'sucos',
                'ordering': ['administrative_post__name', 'name'],
                'unique_together': {('administrative_post', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PreschoolEnrollmentOptIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('portal', 'Portal Prompt')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preschool_enrollment_optins',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('year_of_birth', models.PositiveSmallIntegerField()),
                ('age_group', models.CharField(choices=[('A', 'Group A: 3-4 years'), ('B', 'Group B: 5-6 years')], max_length=1)),
                ('user_id', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'children',
            },
        ),
        migrations.CreateModel(
            name='AppUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('Numero', 'Numbers'), ('Lian', 'Language'), ('Arte', 'Art'), ('Motri', 'Motor Skills'), ('Sosyal', 'Social Skills')], max_length=20)),
                ('group', models.CharField(choices=[('A', 'Group A: 3-4 years'), ('B', 'Group B: 5-6 years')], max_length=1)),
                ('is_assessed', models.BooleanField(default=False)),
                ('was_successful', models.BooleanField(default=False)),
                ('date_accessed', models.DateField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core.child')),
            ],
            options={
                'db_table': 'app_usage_logs',
            },
        ),
        migrations.CreateModel(
            name='ApkVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=20)),
                ('download_url', models.URLField()),
                ('is_latest', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apk_versions',
                'indexes': [models.Index(fields=['is_latest'], name='apk_version_is_late_fbfdc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('suco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='core.suco')),
            ],
            options={
                'db_table': 'aldeias',
                'ordering': ['suco__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='administrativepost',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_posts', to='core.municipality'),
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('access', 'Access'), ('completed', 'Completed'), ('incompleted', 'Incompleted')], default='access', max_length=20)),
                ('category1', models.TextField(blank=True, null=True)),
                ('category2', models.TextField(blank=True, null=True)),
                ('category3', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, null=True)),
                ('activity_result', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='sid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_results', to='core.child')),
            ],
            options={
                'db_table': 'activity_result',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='administrative_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.administrativepost'),
        ),
        migrations.AddField(
            model_name='user',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.aldeia'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.municipality'),
        ),
        migrations.AddField(
            model_name='user',
            name='suco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.suco'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('municipality', 'Municipality'), ('town', 'Town'), ('village', 'Village')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.location')),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['type'], name='locations_type_f5c4b7_idx'), models.Index(fields=['parent'], name='locations_parent__2c2f77_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent'], name='children_parent__dc54ff_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['age_group'], name='children_age_gro_bcb449_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['user_id'], name='children_user_id_461969_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagelog',
            index=models.Index(fields=['child', 'date_accessed'], name='app_usage_l_child_i_018397_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagelog',
            index=models.Index(fields=['theme'], name='app_usage_l_theme_743d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagelog',
            index=models.Index(fields=['activity_type'], name='app_usage_l_activit_7fcf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagelog',
            index=models.Index(fields=['date_accessed'], name='app_usage_l_date_ac_97761f_idx'),
        ),
        migrations.AddIndex(
            model_name='appusagelog',
            index=models.Index(fields=['is_assessed', 'was_successful'], name='app_usage_l_is_asse_ab5d65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aldeia',
            unique_together={('suco', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='administrativepost',
            unique_together={('municipality', 'name')},
        ),
        migrations.AddIndex(
            model_name='activityresult',
            index=models.Index(fields=['parent'], name='activity_re_pid_1582ef_idx'),
        ),
        migrations.AddIndex(
            model_name='activityresult',
            index=models.Index(fields=['student'], name='activity_re_sid_b1a2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['whatsapp_number'], name='users_whatsap_a8914c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'municipality'], name='users_role_dcb365_idx'),
        ),
    ]
