# Generated by Django 4.2.24 on 2026-02-19 00:40

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apkversion',
            name='download_url',
        ),
        migrations.AddField(
            model_name='apkversion',
            name='apk_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=core.models.apk_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appusagelog',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A: Tinan 34 '), ('B', 'Grupo B: Tinan 5-6 ')], max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='age_group',
            field=models.CharField(choices=[('A', 'Grupo A: Tinan 34 '), ('B', 'Grupo B: Tinan 5-6 ')], max_length=1),
        ),
    ]
