# Generated by Django 4.2.24 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_apkversion_download_url_apkversion_apk_file_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apkversion',
            name='apk_version_is_late_fbfdc6_idx',
        ),
        migrations.AlterField(
            model_name='appusagelog',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A: Tinan 3-4 '), ('B', 'Grupo B: Tinan 5-6 ')], max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='age_group',
            field=models.CharField(choices=[('A', 'Grupo A: Tinan 3-4 '), ('B', 'Grupo B: Tinan 5-6 ')], max_length=1),
        ),
    ]
