# Generated by Codex on 2026-05-30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_apkversion_apk_version_is_late_fbfdc6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkversion',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.apk_upload_path),
        ),
        migrations.AddField(
            model_name='apkversion',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
