# Generated by Django 4.2.24 on 2026-06-08 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('preschools', '0004_remove_preschoolteacher_joined_at_and_more'),
        ('core', '0004_apkversion_download_url_apkversion_apk_file_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('activity', 'Activity'), ('other', 'Other')], default='activity', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_theme', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed')], default='success', max_length=30)),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_activity_logs', to='preschools.preschool')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher'], name='teacher_act_teacher_cb6447_idx'), models.Index(fields=['preschool'], name='teacher_act_prescho_6da112_idx'), models.Index(fields=['action_type'], name='teacher_act_action__00c546_idx'), models.Index(fields=['activity_date'], name='teacher_act_activit_f5b8c7_idx')],
            },
        ),
    ]
