# Generated by Django 4.2.24 on 2025-11-23 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category1', models.TextField(blank=True, null=True)),
                ('category2', models.TextField(blank=True, null=True)),
                ('category3', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, null=True)),
                ('activity_result', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='sid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_results', to='core.child')),
            ],
            options={
                'db_table': 'activity_result',
                'indexes': [models.Index(fields=['parent'], name='activity_re_pid_1582ef_idx'), models.Index(fields=['student'], name='activity_re_sid_b1a2d0_idx')],
            },
        ),
    ]
