# Generated by Django 4.2.24 on 2026-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacheractivitylog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teacheractivitylog',
            name='teacher_act_action__00c546_idx',
        ),
        migrations.RemoveField(
            model_name='teacheractivitylog',
            name='action_type',
        ),
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
