# Generated by Django 4.2.24 on 2026-07-08 01:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_timesta_e93820_idx',
            old_name='audit_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_e11c73_idx',
            old_name='audit_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_31f574_idx',
            old_name='audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_module_f52b4d_idx',
            old_name='audit_module_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_status_515e02_idx',
            old_name='audit_status_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='apk/user.jpg', null=True, upload_to=core.models.user_image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent/Carer'), ('moe_admin', 'MoE Admin'), ('moe_auditing', 'MoE Auditing'), ('municipality_analyst', 'Municipality Analyst'), ('teacher', 'Teacher')], max_length=30),
        ),
    ]
