# Generated by Django 4.2.24 on 2026-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_default_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
