# Generated by Django 4.2.24 on 2026-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_log_status_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('mane', 'Mane'), ('feto', 'Feto'), ('indeterminante', 'Indeterminante')], max_length=20, null=True),
        ),
    ]
