# Generated by Django 4.2.24 on 2026-07-29 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('manorin', 'Manorin'), ('koordenador', 'Koordenador')], max_length=20)),
                ('assigned_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_positions',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
    ]
