# Generated by Django 4.2.24 on 2026-05-22 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klase', '0001_initial'),
        ('preschools', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_history', to='preschools.preschool'),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='old_preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_equipment_history', to='preschools.preschool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klase.classroom'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preschools.preschool'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmovementitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='assetmovementitem',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.assetmovement'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preschools.preschool'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
