# Generated by Django 4.2.24 on 2026-06-01 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klase', '0003_classroom_group_classroom_teacher_and_more'),
        ('preschools', '0004_remove_preschoolteacher_joined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='klase.classroom'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='preschools.preschool'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_legacy', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='new_preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_history_legacy', to='preschools.preschool'),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='old_preschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_equipment_history_legacy', to='preschools.preschool'),
        ),
        migrations.CreateModel(
            name='EquipmentAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='equipment.equipment')),
                ('new_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_assignments', to='klase.classroom')),
                ('new_preschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_assignments', to='preschools.preschool')),
                ('new_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_assignments', to=settings.AUTH_USER_MODEL)),
                ('old_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_equipment_assignments', to='klase.classroom')),
                ('old_preschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_equipment_assignments', to='preschools.preschool')),
                ('old_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_equipment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_assignment_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
