# Generated by Django 4.2.24 on 2026-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_options_equipment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('projector', 'Projector'), ('screen', 'Screen'), ('adapter', 'Adapter')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('damaged', 'Damaged'), ('retired', 'Retired')], db_index=True, default='active', max_length=20),
        ),
    ]
