# Generated by Django 4.2.24 on 2026-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('projector', 'Projector'), ('screen', 'Screen'), ('dongle', 'Dongle'), ('power_extension', 'Power Extension')], db_index=True, max_length=30),
        ),
    ]
