# Generated by Django 4.2.24 on 2026-05-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klase', '0001_initial'),
        ('preschools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='preschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='preschools.preschool'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomchild',
            unique_together={('classroom', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('preschool', 'name')},
        ),
    ]
