# Generated by Django 4.2.24 on 2026-05-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='group',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroomchild',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='klase.classroom'),
        ),
    ]
