# Generated by Django 4.2.24 on 2026-07-22 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klase', '0003_classroom_group_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classroomchild',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
