# Generated by Django 4.2.24 on 2026-05-22 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_apkversion_apk_version_is_late_fbfdc6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preschool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('preschool_type', models.CharField(choices=[('government', 'Government'), ('community', 'Community'), ('private', 'Private'), ('playgroup', 'Playgroup')], max_length=30)),
                ('whatsapp_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrative_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.administrativepost')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aldeia')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preschools', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.municipality')),
                ('suco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suco')),
            ],
            options={
                'db_table': 'preschools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreschoolTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preschoolteacher',models.DateTimeField(auto_now_add=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('preschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='preschools.preschool')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_preschools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preschool_teachers',
                'unique_together': {('preschool', 'teacher')},
            },
        ),
    ]
