# Generated by Django 4.2.24 on 2026-05-22 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preschools', '0002_remove_preschoolteacher_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschoolteacher',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
