# Generated by Django 4.2.24 on 2026-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschools', '0004_remove_preschoolteacher_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preschool',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preschool',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
