# Generated by Django 4.2.24 on 2026-05-30 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klase', '0003_classroom_group_classroom_teacher_and_more'),
        ('preschools', '0004_remove_preschoolteacher_joined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='details',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='klase.classroom'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_equipment_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_training_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='preschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='preschools.preschool'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(default=ticket.models.generate_ticket_number, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='SupportTicketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('projector_lamp', '1. Troka lâmpada projetor'), ('miracast_config', '2. Ajuda atu halo konfigurasaun Miracast (tablet Android ba projetor Epson)'), ('projector_support', '3. Suporta projetor – hadia ka troka'), ('screen_problem', '4. Tela klen – problema'), ('tablet_technical', '5. Tablet – problema tékniku'), ('tablet_lost', "6. Tablet – na'ok"), ('tablet_damaged', '7. Tablet – estragu'), ('projector_damaged', "8. Projetor – estragu ka la funsiona la'ós ho lâmpada"), ('cable_adapter', '9. Problema ho kabelu ka adaptador (HDMI, USB-C, etc.)'), ('other_equipment', '10. Problema seluk ho ekipamentu AV iha sala aula'), ('general_training', "11. Husu formasaun jerál ba mestri kona-ba uza aplikasaun ne'e ba ensinu")], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('preferred_format', models.CharField(blank=True, help_text='Preferred training format (ex.: hadau hadap malu, vídeo guia, workshop ho grupu, 1:1)', max_length=255, null=True)),
                ('app_features_to_learn', models.TextField(blank=True, help_text='Application features to learn (ex.: navigasaun, konfigurasaun, jestaun klase)', null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ticket.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_items',
            },
        ),
    ]
