# Generated by Django 4.2.24 on 2026-06-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('training', 'Training')], max_length=20)),
                ('item_key', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('preferred_format', models.CharField(blank=True, max_length=255, null=True)),
                ('app_features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ticket.supportticket')),
            ],
        ),
    ]
